package com.darkx.message.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val DarkColors = darkColorScheme(
    primary = Color(0xFF8E9BFF),
    onPrimary = Color(0xFF0A1040),
    primaryContainer = Color(0xFF2B3585),
    onPrimaryContainer = Color(0xFFDDE0FF),
    secondary = Color(0xFFB6BEDA),
    onSecondary = Color(0xFF1F2640),
    secondaryContainer = Color(0xFF353D5A),
    onSecondaryContainer = Color(0xFFDAE0FF),
    tertiary = Color(0xFF5AD1C8),
    onTertiary = Color(0xFF00201E),
    tertiaryContainer = Color(0xFF00504B),
    onTertiaryContainer = Color(0xFFA0F2EA),
    background = Color(0xFF0A0C10),
    onBackground = Color(0xFFE6E8EE),
    surface = Color(0xFF10131A),
    onSurface = Color(0xFFE6E8EE),
    surfaceVariant = Color(0xFF1A1F29),
    onSurfaceVariant = Color(0xFFA3AAB8),
    surfaceContainerLowest = Color(0xFF080A0E),
    surfaceContainerLow = Color(0xFF0F1319),
    surfaceContainer = Color(0xFF151A22),
    surfaceContainerHigh = Color(0xFF1B212B),
    surfaceContainerHighest = Color(0xFF222936),
    outline = Color(0xFF6A7283),
    outlineVariant = Color(0xFF2A303C),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
)

internal val LightColors = lightColorScheme(
    primary = Color(0xFF4350D6),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE0E2FF),
    onPrimaryContainer = Color(0xFF000A6B),
    secondary = Color(0xFF5A6075),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDEE1F9),
    onSecondaryContainer = Color(0xFF161B2C),
    tertiary = Color(0xFF006A64),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF9CF1E9),
    onTertiaryContainer = Color(0xFF00201E),
    background = Color(0xFFFAF9FF),
    onBackground = Color(0xFF1B1B1F),
    surface = Color(0xFFFAF9FF),
    onSurface = Color(0xFF1B1B1F),
    surfaceVariant = Color(0xFFE3E1EC),
    onSurfaceVariant = Color(0xFF46464F),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F3FA),
    surfaceContainer = Color(0xFFEFEDF4),
    surfaceContainerHigh = Color(0xFFE9E7EF),
    surfaceContainerHighest = Color(0xFFE3E1E9),
    outline = Color(0xFF777680),
    outlineVariant = Color(0xFFC7C5D0),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
)
